name: yourbillz
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.5.2"
  
  dio:

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/yourbillz_new_logo.png"
  image_path_android: "assets/yourbillz_new_logo.png"
  image_path_ios: "assets/yourbillz_new_logo.png"

flutter:
  uses-material-design: true

  assets:
   - assets/splash_screen.jpg
   - assets/loginbackground.png
   - assets/profile.png
   - assets/registration_selector.jpg
   - assets/main_registration.jpg

  fonts:
    - family: Monaco
      fonts:
        - asset: fonts/Monaco-Linux.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Light.ttf
        - asset: fonts/Oswald-Medium.ttf
        - asset: fonts/Oswald-Regular.ttf

